### ISSUE TITLE
I would like to open multiple instances of modal box.

### ISSUE THREAD

**Issue by dhirnitish** [kylefox/jquery-modal#101]
I am trying to open multiple modal boxes by providing link to second modal box in the first modal box. 

Second modal box opens successfull but it closes the first one. Is that possible?

**Comment by greensn0w** [comment]
The answer to this, is in the README.md:

> Because there can be only one modal active at a single time [...]

**Comment by voiski** [comment]
But look this case:

> I will use a modal to get some answers, but I need a second modal for ajax event loading. I cant do that with current plugin. I will rewrite something different to do that =/

Or
> I will use a modal to get some answers, in one field I need to open a second modal to made a more precise search using filter fields for example. In this case, I can't do that, I need to change the solution.
