### ISSUE TITLE
Fade Transitions

### ISSUE THREAD

**Issue by 185driver** [kylefox/jquery-modal#103]
Hi, very nice tool!  Thank you.

I noticed in the fade transition section of the docs that it says, "there are no transitions when closing the modal." However, my experience is that whatever fade transition has been set for fade in will be used during fade out automatically. This is mostly noticeable when the transition duration is set to a higher value.

**Comment by kylefox** [comment]
You're right, thanks for pointing it out — I updated the documentation to reflect this in 334b18a1a16da5bee9f8a44e4df62ca3ea96f0be.
