### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by kevadamson** [kylefox/jquery-modal#104]
Had to do a bit of a hack to make responsive. Perhaps what I've done can become proper options?

In the JS line 146 (changed left to 0 and removed marginLeft):

```
center: function() {
  this.$elm.css({
    position: 'fixed',
    top: "50%",
    // left: "50%",
    left: "0",
    marginTop: - (this.$elm.outerHeight() / 2),
    // marginLeft: - (this.$elm.outerWidth() / 2),
    zIndex: this.options.zIndex + 1
  });
}
```

Included inner div and close button to the HTML, so:

```
<div id="test" class="modal">
  <div>
    Test
    <a href="#" rel="modal:close">Close</a>
  </div>
</div>
<a href="#test" data-modal>Modal</a>
```

Wrote my own CSS:

```
.modal { display: none; width: 100%; padding: 30px; }
.modal > div { background-color: #fff; padding: 30px; max-width: 640px; margin-left: auto; margin-right: auto; }
```

Set options to the following:

```
$('a[data-modal]').click(function(event) {
  $(this).modal({
    showClose: false, //because need my own button inside div for position flexibility
    clickClose: false //because the the padding/space to left and right of modal won't close the modal
  });
  return false;
});
```

^ pointer-events: none; in CSS on .modal, and then pointer-events: auto; on the div would mean you could keep clickClose, but pointer-events haven't got great browser support ...

Thoughts?

**Comment by VersatilityWerks** [comment]
jAlert is natively responsive and badass :) 
http://flwebsites.biz/jAlert/

**Comment by COLABORATI** [comment]
Thank you very much for the jAlert link, this looks great!

**Comment by VersatilityWerks** [comment]
No problem :)

**Comment by philip** [comment]
I think this should be a top request, so consider this a +1 to auto-sizing the width.

**Comment by magicjoef** [comment]
I used a little bit of CSS to convert mine to a flexible width. I wanted it flexible, but maximum of 800px:

.modal {
  width:100%;
  max-width:800px;
}

This worked nicely with Foundation framework, which I'm using to structure the content in my modals.

**Comment by kylefox** [comment]
This is just a note that [v0.8.0](https://github.com/kylefox/jquery-modal/tree/v0.8.0) is much more mobile/responsive friendly. The modal has `width: 90%;` rather than a pixel value, along with a `max-width: 500px;` to prevent extremely wide content on larger screens.
