### ISSUE TITLE
Bower release v0.5.5

### ISSUE THREAD

**Issue by frontdevltd** [kylefox/jquery-modal#105]
Hi 

When will there be a bower v0.5.5 release as version v0.5.2 does not have the fadeDuration and fadeDelay functionality!

**Comment by kylefox** [comment]
Hi, I don't really use bower so I would recommend submitting a pull-request with the changes you'd like. Thanks.

**Comment by frontdevltd** [comment]
Hi,
Sorry for the delayed response, there are no changes that are required, what I was asking was would version 0.5.5 be pushed for release as when I do a bower install of the plugin the latest release points to 0.5.2 and I require 0.5.5 hope this makes sense?

**Comment by zaach** [comment]
You should be able to just tag 0.5.5 and push it to github.

**Comment by kylefox** [comment]
Done, should be available: `bower info jquery-modal#0.5.5` will display the package.
