### ISSUE TITLE
re-trigger vertical position after window size change?

### ISSUE THREAD

**Issue by frumbert** [kylefox/jquery-modal#106]
If the height of the content changes during the time the modal is on screen, say by dynamically adding content, the window position doesn't re-center vertically. Resizing the browser will reposition the dialog but doesn't take into account its new height.

**Comment by VersatilityWerks** [comment]
Try jAlert http://flwebsites.biz/jAlert/

**Comment by adriaanmeuris** [comment]
Centering of the pop-up could be greatly improved by not using margin top/left for positioning, but using a css transform property, e.g. translate: transform(-50%, -50%).

**Comment by kylefox** [comment]
@frumbert As far as I can tell, the resizing/positioning seems to work _alright_ — see Example 3 on [jquerymodal.com](http://jquerymodal.com/)

@adriaanmeuris I agree, using CSS transforms would be a huge improvement. I might take a stab at that soon.

I'm going to close this issue but will reopen it if a test-case is provided. Thanks!
