### ISSUE TITLE
Link with href="#" not related to the plugin pop up the overlay

### ISSUE THREAD

**Issue by ketri** [kylefox/jquery-modal#108]
I'm using the DMS wordpress-theme. There's plenty of buttons with <a href="#">. When I click one of these, the jquery modal plugin gets activated.  

So cases where there might be this kind of empty links should probably be taken into account.

Thanks!

**Comment by gnesher** [comment]
+1

**Comment by kylefox** [comment]
Can you please provide a publicly-accessible web page that demonstrates the issue?

Modal functionality is only added to the links you specify with `rel="modal:open"` (or manually open). So I am unsure of how the overlay could possibly be triggered by non-modal links. Thanks!
