### ISSUE TITLE
Ajax modals not destroying themselves on close

### ISSUE THREAD

**Issue by BenComicGraphics** [kylefox/jquery-modal#109]
Go to http://fng.steadfastlight.com/#catering-section and click on the middle button.  THen close, then open it again.  The modal is being replicated eahc time without being destroyed.

**Comment by kkutschera** [comment]
Up!

**Comment by kkutschera** [comment]
Check if you got the modal-script in the ajax-content too ;)

**Comment by kylefox** [comment]
Did you solve this? In my tests the AJAX modals appear to be closing for me...

Note that AJAX modal are only destroyed automatically when using [Method 1: Automatically attaching to links](https://github.com/kylefox/jquery-modal#method-1-automatically-attaching-to-links) to open the modal, ex: `<a href="ajax.html" rel="modal:open">example</a>`

If you're using [Method 2: Manually](https://github.com/kylefox/jquery-modal#method-2-manually) to bind to the `click` event and inject the AJAX data into a modal, you'll need to manage the removing of that modal yourself.

**Comment by mtkennedy** [comment]
To get the modal to remove using Method 2: of the Ajax, I modified the 'unblock' function like this: 

    unblock: function() {
      if(this.options.doFade) {
        this.blocker.fadeOut(this.options.fadeDuration, function() {
          $(this).remove();
		  $('.modal').remove();
        });
      } else {
        this.blocker.remove();
      }
    },


Does what I want it to.
