### ISSUE TITLE
Please release your new code

### ISSUE THREAD

**Issue by Hazarapet** [kylefox/jquery-modal#114]
Please release your new code,because in v 0.5.2 there is not any fade option

**Comment by denis-sokolov** [comment]
This is probably a duplicate of #105.

**Comment by Hazarapet** [comment]
I didn't see it

**Comment by denis-sokolov** [comment]
I know, that's why I helpfully provided a link. If that issue seems suitable enough for your needs, you may close this one.

**Comment by kylefox** [comment]
Done, should be available: `bower info jquery-modal#0.5.5` will display the package.
