### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by ddofborg** [kylefox/jquery-modal#116]
We are using this plugin for popup forms. It works GREAT on desktop, but on mobile it does not.

If the popup is higher than the screen you have a problem. When you scroll within popup nothing happens, only the page behind the overlay can be scrolled. Basically you cannot use the form/content in the popup.

Is there a nice way to still place an overlay which can be scrolled, but still takes up the full screen on the phone.

**Comment by nicekiwi** [comment]
Some simple CSS and jQuery can make this work. Like setting the .modal element to absolute positioning to allow it to scroll and setting the correct with and height variables to make it take up as much space is needed. 

And override the 'top' and 'margin-top' variables to however far you want it from the top of the page.

**Comment by ddofborg** [comment]
I fixed it like that :) But I think a general solution within the plugin might be a better option :)

**Comment by kylefox** [comment]
This is just a note that [v0.8.0](https://github.com/kylefox/jquery-modal/tree/v0.8.0) is much more mobile/responsive friendly. The modal has `width: 90%;` rather than a pixel value, along with a `max-width: 500px;` to prevent extremely wide content on larger screens.
