### ISSUE TITLE
Error with W3C validator

### ISSUE THREAD

**Issue by saltict** [kylefox/jquery-modal#129]
When I check my page with W3C Validator(https://validator.w3.org) throw an error "Bad value modal:open for attribute rel on element a: The string modal:open is not a registered keyword". I think the default way to call modal need to be change

**Comment by kylefox** [comment]
Thanks for the suggestion :) However, I'm not too concerned about W3C Validation and don't think it's worth breaking compatibility for.

**Comment by hultberg** [comment]
@saltict, you could always use click events from javascript instead of link attributes. This would fix this problem in W3C validator.

**Comment by saltict** [comment]
@hultberg Thank you! I have fixed it :) !
