### ISSUE TITLE
How to set the z-index for modals?

### ISSUE THREAD

**Issue by COLABORATI** [kylefox/jquery-modal#131]
I have a usecase where the z-index of the modal is always set to 2, no matter what I write in the modal css. How can I force the modal to have the highest z-index?

BTW this might be an interesting edge-case; I am trying to get a modal for a full screen gallery that was build with photoswipe.com - neither the photoswipe source (js + css) nor jquery-modal contain the string z-index - so this is a nice investigative challenge for the passioned css researcher - wtf is the z-index always 2, even when I set it to 999 in the jquery-modal css file? Unfortunately I have to move on with some other urgent things to be done, but I will reserve some xmas holiday time for this funny yak-shaving session. 

Another BTW: One could have the perception that a core feature of a modal is to be visible on top of any other content. So it might be an explicit top-level (!) requirement for good modal code that it has to be visible in any (edge) case, no matter what happens around it (besides special modal-fighting code, of course). This seems to be, looking closer at it, the only real requirement for robust modal code - show the f* modal in any situation. So to make the modal code really robust it would be an interesting thing to start collecting test cases for situations, where this does not work. I would like to suggest to start doing exactly this. Please make a wiki or create another repo where people can put their non-working (edge) cases, so we can all collect lots of material for the "html 5 modal university". 

This will be a great way to finally publish a modal plugin that works - everywhere.

**Comment by kylefox** [comment]
Did you try adjusting the `zIndex` in the [Options?](https://github.com/kylefox/jquery-modal#options)

**Comment by adods** [comment]
I have the same problem and the `zIndex` option seems doesn't work on the last version, even the option is gone from the readme. And without z-index modification, the modal appear in the back of my content, and can't be closed

**Comment by kylefox** [comment]
It looks like `zIndex` was removed from options — I actually don't recall when :smile: 

Anyway — have you tried specifying it with  CSS?

```css
.blocker  { z-index: 100; }
.modal    { z-index: 101; }
```

**Comment by temitope** [comment]
running into this same issue, where I need to adjust zIndex.
