### ISSUE TITLE
Automatic bind links for 'rel' attribute with multiple values

### ISSUE THREAD

**Issue by willduarte** [kylefox/jquery-modal#135]
Just a little improvement for automatic binds to links.

I found this problem when i needed add "nofollow" for some SEO treatments in my projects.

Just change the selectors below to "a[rel~="modal:close"]" and "a[rel~="modal:open"]" instead of ```rel="..."```.

```
...

$(document).on('click.modal', 'a[rel="modal:close"]', $.modal.close);
$(document).on('click.modal', 'a[rel="modal:open"]', function (event) {
    event.preventDefault();
    $(this).modal();
});

...
```

**Comment by kylefox** [comment]
Good catch, thanks for the fix!
