### ISSUE TITLE
Nested Modal

### ISSUE THREAD

**Issue by Sharagim** [kylefox/jquery-modal#137]
Hi,
Is there any way to have nested modal?
As i see second one clean first modal and by closing last one all is going.
BR,

**Comment by kylefox** [comment]
It's not currently possible to have multiple modals without closing the existing modals (as shown in [Example 6: Multiple Modals](http://kylefox.ca/jquery-modal/examples/index.html)).

If you need to "stack" modals I would suggest either:

1. Manipulating the content of the open modal (rather that popping open additional modals), or
1. Submitting a pull request with this functionality :smile:
