### ISSUE TITLE
Fade transition only works on initial click

### ISSUE THREAD

**Issue by angieherrera** [kylefox/jquery-modal#138]
Apologies for not having code for viewing, but the issue is present in the [demo](http://kylefox.ca/jquery-modal/examples/index.html). 

Under _Example 7: Fade Transitions_, clicking on the first basic fade transition, the modal fades in. Closing the modal, and then clicking to open again, the modal never appears. In fact, this is the case with all three fade transition examples.

**Comment by kylefox** [comment]
Good catch, thanks for reporting! Fixed in 0.6.1.
