### ISSUE TITLE
Firing the modal on page load

### ISSUE THREAD

**Issue by s0rfila** [kylefox/jquery-modal#139]
Curious if it's possible to automatically fire the modal on page load, rather then clicking the anchor. I'm assuming it's rather simple, but I haven't been able to get it to fire without the `<a>`, I've got it working perfectly like the examples.. apologies as I'm sure this is possible with jQuery, and not an actual issue with your plugin. However, StackOverflow is tango-down today on read-only mode so I thought I'd ask here real quick

**Comment by kylefox** [comment]
It's possible to automatically open the modal when the page loads.

You need to do so using the standard [`jQuery(callback)`](http://api.jquery.com/jQuery/#jQuery3) pattern so that the DOM is fully loaded.

For example:

```javascript
$(function() {
  $('#login-form').modal();
});
```
