### ISSUE TITLE
href page title appears at top left of the screen before modal windows appear !

### ISSUE THREAD

**Issue by DailyciousInfo** [kylefox/jquery-modal#141]
Hi,

When I add the script to add a fadeduration to my modal windows, the href page title appear at the top left of the screen and then disappear when the modal windows is loaded.

How can I fix this ?

By the way, thanks for this script. It's wonderful !

**Comment by DailyciousInfo** [comment]
My bad.. the error come from my css ! 

Really sorry for this ticket.

**Comment by kylefox** [comment]
Cool, no worries — glad you got it figured out!
