### ISSUE TITLE
How to prevent falling into single.php when I hit the url project ?

### ISSUE THREAD

**Issue by DailyciousInfo** [kylefox/jquery-modal#143]
Hi, first of all, thank you for this script.. it work pretty well !

Unfortunately, I have a issue.

I'm building a theme for Wordpress. I have custom portfolio posts that list all of my posts one after the other on my homepage and when I click on it, a modal window is loaded over my homepage and show the content (which is the single.php btw). It work like a charm !

But, if I load the project directly with the url (ex: www.mydomain.com/project-1), it load the single.php. I would like to load my single.php in my modal window over the homepage...

Is it possible ? I search a way since so many days :'(

I think it's possible to redirect visitors to the homepage and then add a trigger to load the post in modal window.. isn't it ?

**Comment by kylefox** [comment]
It's impossible for me or anyone else to troubleshoot this issue without a live demonstration of the problem. Please review the [README](https://github.com/kylefox/jquery-modal#bugs--feature-requests).

I am going to close this, but I will re-open if you can provide a demonstration of the problem. Thanks.
