### ISSUE TITLE
Modal not hiding and showing at bottom of <body> on close

### ISSUE THREAD

**Issue by Farsk** [kylefox/jquery-modal#145]
Needed to modify close function of JS

I changed:
`this.hide()`

To:
`$(this.$elm).attr('style', 'display: none !important')`

This issue is caused by the conflict of display: inline-block **!important** in the modal CSS and style="display: none;" from the hide method.

Seems to be working correctly now. My testing was done in OSX Firefox (latest). It would probably be better to apply a fixed to the plugin's hide function directly.

**Comment by kylefox** [comment]
I haven't been able to reproduce this issue (see examples on [jquerymodal.com](http://jquerymodal.com/)).

If you're still seeing this behaviour, please provide a publicly-accessible example (i.e. [codepen.io](http://codepen.io/)) that demonstrates the bug. Thanks!
