### ISSUE TITLE
Auto-open modal on page load

### ISSUE THREAD

**Issue by collizo4sky** [kylefox/jquery-modal#149]
Any idea / pointer how to achieve this?

**Comment by kylefox** [comment]
Have a look at #139 

```javascript
$(function() {
  $('#login-form').modal();
});
```

**Comment by gorillamoe** [comment]
Look, [this](https://pwny.gorilla.moe/#!/?s=html&c=9&l=11&t=5d00000002e301000000000000001e1cc86755bb63d868551718ad8cbae957433adc0f6afa4a15a0ffa881ce6495bddea1d0149519ff7acef25a95954195caa03b5d603355ca3e56a083c97d48b61be54d4f37445d813dbcee183a99f70e49a74d6bd57bddd96530ac1cb111e8e8faa23af725be38716d6f2c38fbd00d9b64ab5b6b06fc7e0f500d08c44718ae6a3df28b73a3567b848291b7be44a30b46d07a56e7addafa4f0105951482b10bad94cd65c5a468cceec739513a15fa408b075c46e9f8f5b688201056f7f7c85a1d76ec8b6e21d449ba0cffcf06b682360f62f2430c87dc82febf9b36b34860ecd4370a70151adb6cc066e0a033fa9d54571016fec2eee3c5ab815a44c6dddc9d9c6ae3b2949547629ff7def6ffed970565) works for me :)
