### ISSUE TITLE
Modal not growing automatically with the content

### ISSUE THREAD

**Issue by bfleishman** [kylefox/jquery-modal#151]
I have a textarea that I am showing in my modal. It has the following attributes: cols="100" rows="20" . Since the modal is set to 400px by default, the content expands over the right side of the modal. I've attached a screenshot.

Is there a way to have the modal automatically resize?

![image](https://cloud.githubusercontent.com/assets/360187/14028185/a0d7e1e6-f1d1-11e5-8543-1632f78401a4.png)

**Comment by kylefox** [comment]
The modal doesn't automatically resize horizontally.

A couple solutions you can try:

(1) Specify a `width` on your textarea, rather than use `cols`:

```css
.modal textarea { width: 90%; }
```

Or,

(2) Adjust the width of the modal statically width CSS:

```css
.modal { width: 100em; }
```

or dynamically with JavaScript after the modal opens:

```javascript
$('#my-modal').on('modal:open', function(event, modal) {
  var textarea = modal.elm.find('textarea');
  modal.elm.css('width', textarea.width());
});
```

**Comment by bfleishman** [comment]
I found that setting

width: auto;

in CSS for .modal does the trick. Thanks.

Best Regards,

Brian Fleishman

|\ Need Immediate Help? Email the support Desk: support@jaydien.com<mailto:support@jaydien.com> /|
