### ISSUE TITLE
viewport

### ISSUE THREAD

**Issue by michaellct** [kylefox/jquery-modal#152]
when i add viewport attribute,display is so strange,not centered,but bootm,help!
 <meta name="viewport" content="width=device-width, initial-scale=1">

![image](https://cloud.githubusercontent.com/assets/15043716/14073287/633690b8-f4fa-11e5-9f1f-ec6ae0e51be5.png)
![image](https://cloud.githubusercontent.com/assets/15043716/14073291/6b8a7a0e-f4fa-11e5-94ea-aa97ce9ba227.png)

**Comment by michaellct** [comment]
I resolved this by uncomment modal class's width attribute.
/*width: 400px;*/
is there any other solution?

**Comment by hultberg** [comment]
You could just override the width with CSS using media queries.
````
@media (max-width: 500px) {
  .modal { width: 100% !important; }
}
````

**Comment by michaellct** [comment]
@hultberg  thank you very much!

**Comment by michaellct** [comment]
100%  not solve the problem,i changed to 80%,it worked
@media (max-width: 500px) {
  .modal { width: 80% !important; }
}

**Comment by kylefox** [comment]
This is just a note that [v0.8.0](https://github.com/kylefox/jquery-modal/tree/v0.8.0) is much more mobile/responsive friendly. The modal has `width: 90%;` rather than a pixel value, along with a `max-width: 500px;` to prevent extremely wide content on larger screens.
