### ISSUE TITLE
$('div').modal() then element 'display' attribute turn into 'block'

### ISSUE THREAD

**Issue by oxbambooxo** [kylefox/jquery-modal#153]
I use the latest version jquery-modal, but in using, the div's display attribute final become the 'block',
becase it using the $.show() in div, then final the div display will be 'block'.
i patch that modify the $.modal.prototype.open function in following:

    $.modal.prototype.open = function() {
      var m = this;
      this.block();
      if(this.options.doFade) {
        setTimeout(function() {
          m.show();  // $('div').show(); make the div's display attribute become 'block'
          m.$elm.css('display', 'inline-block');  // i add this line
        }, this.options.fadeDuration * this.options.fadeDelay);
      } else {
        this.show();
      }
      $(document).off('keydown.modal').on('keydown.modal', function(event) {
        var current = getCurrent();
        if (event.which == 27 && current.options.escapeClose) current.close();
      });
      if (this.options.clickClose)
        this.$blocker.click(function(e) {
          if (e.target==this)
            $.modal.close();
        });
    }

**Comment by oxbambooxo** [comment]
Does anyone have a better solution yet?

**Comment by kylefox** [comment]
I don't exactly understand what you're trying to do, or what the problem is — can you explain further please? 

Link to a public test case if at all possible.

Thanks.

**Comment by oxbambooxo** [comment]
sorry, because I used the wrong method.
looking the example is use <a href='#MyDiv'>, then $('a').modal() is ok.
but my bad method is $('#MyDiv').modal().

**Comment by kylefox** [comment]
Ah, ok. Glad you got it figured out 👍
