### ISSUE TITLE
How to trigger action on ajax modal close?

### ISSUE THREAD

**Issue by daysleeperrr** [kylefox/jquery-modal#155]
There is a nice feature for non-ajax modals, to trigger any javascript code when the modal is closed. It is described in the docs: https://github.com/kylefox/jquery-modal#events

> $('#purchase-form').on($.modal.BEFORE_CLOSE, function(event, modal) {
>   clear_shopping_cart();
> });

But, this only applies to non-ajax modals. For ajax modals, there are a few other events:

> $.modal.AJAX_SEND = 'modal:ajax:send';
> $.modal.AJAX_SUCCESS = 'modal:ajax:success';
> $.modal.AJAX_FAIL = 'modal:ajax:fail';
> $.modal.AJAX_COMPLETE = 'modal:ajax:complete';

These are triggered on the anchor that initiated the modal. I've tested, and there is indeed no BEFORE_CLOSE working on that anchor. So does anyone know how to trigger some code when an ajax modal is closed (either by clicking the cross, pressing escape, clicking the overlay, whatever).

**Comment by daysleeperrr** [comment]
This might be the same issue as mentioned here:
https://github.com/kylefox/jquery-modal/issues/113

**Comment by emkae** [comment]
See for a working example: https://github.com/kylefox/jquery-modal/issues/203#issuecomment-307621636

This can be closed.
