### ISSUE TITLE
Clashes (a.k.a, doesn't work) alongside Select2 

### ISSUE THREAD

**Issue by madebyelmcity** [kylefox/jquery-modal#156]
Hello: Couldn't figure out why my modals suddenly weren't working. Through a bit of trial-and-error, found that removing Select2 (https://select2.github.io/) fixed the issue.

No error messages in Console to indicate what may be causing the issue.

**Comment by kylefox** [comment]
Please link to a publicly-accessible demonstration of the problem. Thanks.

**Comment by emkae** [comment]
Shouldn't this issue be closed, due to the lack information and activity of @madebyelmcity ?
