### ISSUE TITLE
jQuery version requirements blocks use of jQuery 2.2.x

### ISSUE THREAD

**Issue by FlyingDR** [kylefox/jquery-modal#157]
Your current [version specification](https://github.com/kylefox/jquery-modal/blob/master/bower.json#L19) for jQuery avoids use of jQuery 2.2 (current version is [2.2.4](https://github.com/jquery/jquery/releases)).

Also since jQuery 3 is coming it will be good to consider testing this plugin with new version.

**Comment by albertborsos** [comment]
+1

**Comment by kylefox** [comment]
Just a quick update, jQuery Modal now supports everything up to jQuery 3.1.x.

https://github.com/kylefox/jquery-modal/blob/master/bower.json#L19
