### ISSUE TITLE
trigger modal on event

### ISSUE THREAD

**Issue by izenn** [kylefox/jquery-modal#158]
I have a javascript event that i currently use alert() on, however i would like to replace that with a modal.  Is it possible to trigger a modal.open from a function and not require clicking a href?

**Comment by kylefox** [comment]
You should be able to [open the modal manually](https://github.com/kylefox/jquery-modal#method-2-manually).

I haven't tested this code, but something like this:

```javascript
function alert(message) {
  // Get your modal markup from the DOM.
  var $myModal = $('#myModal');

  // Inject your message somewhere into the modal.
  $myModal.find('span.message').text(message);

  // Display the modal.
  $myModal.modal();
}
```
