### ISSUE TITLE
Multiple Ajax Modals

### ISSUE THREAD

**Issue by anybodesign** [kylefox/jquery-modal#161]
Hello :)
I'lm trying to have multiple ajax modals... 
the first one triggers properly, but not the others (direct link to the page)
Am I missing something ?

my code : `    jQuery('a.popin[data-modal]').click(function(event) {
      event.preventDefault();
      jQuery.get(this.href, function(html) {
        jQuery(html).appendTo('body').modal({
	        modalClass: 'pop-in'
        });
      });
    });`

**Comment by kylefox** [comment]
Hm. Unfortunately I can't really tell without being able to inspect your page directly. If you can please link to a publicly-accessible page which demonstrates the problem, I can take a look.

Also — is there any reason you can't use the built-in AJAX functionality?

```html
<a href="/page.html" rel="modal:open">Login</a>
```

**Comment by anybodesign** [comment]
Hi,
thanks, I managed to get it work, can't remember what I did exactly…
here is the final code : 

<pre>jQuery('a.popin[data-modal]').click(function(e) {
		e.preventDefault();
		jQuery.get(this.href, function(html) {
			jQuery(html).appendTo('body').modal({
			    modalClass: 'pop-in',
				fadeDuration: 250,
				fadeDelay: 0.80	        
			});
		});
    });
</pre>


and I don't use the built-in functionnality because I need to change the class name of the modal !
