### ISSUE TITLE
Don't use global jQuery

### ISSUE THREAD

**Issue by Cryde** [kylefox/jquery-modal#162]
Hi,

Do you think that it could be possible to "require" jquery in your npm module ?
Because when I use it in my build it said that it doesn't find "jQuery" in the global way.

Thank you for this very good job !

**Comment by Cryde** [comment]
I will do a pull request soon as I can.

Info here : http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm
And the code to add: https://gist.github.com/linclark/2457d5e9d3105f759ebc

**Comment by kylefox** [comment]
Hey, good suggestion. However, I don't really use this library in that context so a PR and example build setup (grunt, gulp, etc) would be awesome. Thanks!

**Comment by Cryde** [comment]
Ok !
I will do a PR soon with a simple example in my repo

**Comment by Cryde** [comment]
I put an example on my repo : https://github.com/Cryde/jquery-modal-as-module-test
And here my 2 commits : https://github.com/Cryde/jquery-modal/commits/master
Nothing fancy.

Tell me when I can PR
