### ISSUE TITLE
$.modal.BEFORE_BLOCK ??

### ISSUE THREAD

**Issue by wzup** [kylefox/jquery-modal#163]
> Hopefully the names are self-explanatory.

No, they are not. 
What is `$.modal.BEFORE_BLOCK`

**Comment by kylefox** [comment]
You're right — I just added [descriptions of the events](https://github.com/kylefox/jquery-modal#events).

The `$.modal.BEFORE_BLOCK` event fires just before the overlay (blocker) appears.

Basically it's the _very_ first thing that fires when a modal begins the process of opening — before the overlay has been added, before the modal begins fading in, etc.
