### ISSUE TITLE
Support for animate.css transition when modal is open and dismissed

### ISSUE THREAD

**Issue by collizo4sky** [kylefox/jquery-modal#165]
@kylefox FadeDelay and fadeDuration is great. It will be even better if we can use any of animate.css transition (http://daneden.github.io/animate.css/). Can you implement this?

**Comment by kylefox** [comment]
Good suggestion — however I don't have time to implement this myself, unfortunately. If you want to tackle it I'd be glad to accept a [pull request](https://help.github.com/articles/using-pull-requests/) for it. Cheers!

**Comment by collizo4sky** [comment]
I think i can tackle it. Will give it a stab this week.

**Comment by kylefox** [comment]
Awesome 👍 

In general, I would actually love to move as much presentation to CSS as possible. Your suggestion is a good reminder that moving away from presentation effects in JS should be a priority...

**Comment by collizo4sky** [comment]
Will let you know how it goes and also inform you of any bummer i come across.

**Comment by svensson-david** [comment]
I needed something similar and did a quick-fix which worked out pretty good. I did not use animate.css but that could be included if needed. I thought I'd share it here for reference, let me know if you want a gist or documentation in some other format.

I'm using the rails-gem which includes a pretty old version of the jquery-modal which means that some of the events and options might have changed names.

Anyway, here goes:
To get animations with css working I added some css transitions and base styles on the modal-class, like opacity: 0; transition: all 0.3s; etc.

Then I disabled the regular fade animation through plugin options and fired a custom function on the modal open event like so:
```
$(document).on($.modal.OPEN, '.modal', function(event, modal) {
  //Needed to add a mini timeout for some reason, not sure why
  setTimeout(function(){$(modal.elm).addClass('in');}, 1);
});
```
The in-class that gets added to the modal has among other things opacity:1 triggering the regular css-transition.

To get the same behavior on close i bound to $('a[rel="modal:close"]').click, preventing default and propagation to make sure the click never reaches the plugin. In the click function I removed the in-class to trigger the animation again and then called the regular plugin close function with after a setTimeout with the same length as the css transition property.

**Comment by kylefox** [comment]
@svensson-david @collizo4sky Thanks for this. I'm considering doing a clean break and outlining a proposal for jquery-modal 2.0 which would (among other things) move all presentation (styling, animations, transitions, etc) to CSS. So any additional thoughts you have based on your experience using CSS with jquery-modal would be appreciated. Thanks!

**Comment by collizo4sky** [comment]
I haven't given my stab on this yet. Hopefully should have something done
this week.

Nice idea @svensson <https://github.com/svensson-david>

**Comment by kylefox** [comment]
Closing this, but will re-open if someone submits a pull request.
