### ISSUE TITLE
AFTER_CLOSE and BEFORE_CLOSE events not working

### ISSUE THREAD

**Issue by nagaraju007** [kylefox/jquery-modal#167]
AFTER_CLOSE or BEFORE_CLOSE is not calling, I checked using debuggers and console logs..
$('#approvetimecard').on($.modal.AFTER_CLOSE, function(event, modal) {
  self.onCancel();
});

**Comment by kylefox** [comment]
Hi, I just double-checked and as far as I can tell `AFTER_CLOSE` is firing. You can check by observing the console while opening/closing modals on http://jquerymodal.com/

Further investigation will require you to link to a publicly-accessible page which demonstrates the bug. Thanks!
