### ISSUE TITLE
Very strange problem with jquery on click

### ISSUE THREAD

**Issue by ibnbd** [kylefox/jquery-modal#171]
I don't know if anyone else experienced this problem or not. I am having a very strange problem with jquery on click function. It's not firing up for elements inside modal.

For example

```
<div id="my_modal">
<input type="button" id="my_button" value="Click">
</div>

<script>
$("#my_button").on("click", function () {
//It's doesn't works
});

$("#my_modal").on("click", function () {
//It works perfect
});
</script>

```

Any solution will be helpful.

Thanks

**Comment by kylefox** [comment]
It's very difficult to debug without a publicly-accessible page that demonstrates the problem.

My _guess_ would be that your `#my_button` element is being added to the page dynamically and the event handler is not being bound. From the [jQuery documentation](http://api.jquery.com/on/#direct-and-delegated-events) for `.on()`:

> Event handlers are bound only to the currently selected elements; they must exist at the time your code makes the call to .on().

What you likely need is *delegated events.* Check out [the jQuery documentation](http://api.jquery.com/on/#direct-and-delegated-events) for more information, but something like this should work:

```javascript
$(document).on("click", "#my_button", function () {
  // Will fire even if #my_button doesn't exist yet.
});
```
