### ISSUE TITLE
return one value form hmtl that show in modal

### ISSUE THREAD

**Issue by jinyistudio** [kylefox/jquery-modal#173]
Hi

I will try to load html file into jquery-modal. I have two button in that html(OK,Cancel) file. Could i return ok/1 or cancel/0 back to its parent page ?

**Comment by malled** [comment]
Yes you can, but that's not related to this plugin.

Use an input element to submit the form like:

<input type="submit" value="1"> Ok
<input type="submit" value="0"> Cancel

**Comment by kylefox** [comment]
@jinyistudio There are many different ways you could approach this problem. The simplest way might be to define a function in your "parent" page and have buttons which call that function.

Your parent page function might look like this:

```javascript
function closeModal(success) {
  if(success) {
    // They clicked "OK"
    alert('You clicked OK!');
  } else {
    // They clicked "Cancel"
    alert('You clicked Cancel!');
  }

  // Close the modal, regardless of which button they clicked.
  $.modal.close();
}
```

And your modal buttons might look like this:

```html
<button onclick="return closeModal(true);">OK</button>
<button onclick="return closeModal(false);">Cancel</button>
```

(I haven't tested this code so you might need to debug it).

As @malled said, this isn't related to the plugin so I can't help further, but hopefully this gives you a starting point. If you still need assistance please try [stackoverflow.com](http://stackoverflow.com/).
