### ISSUE TITLE
React implementation?

### ISSUE THREAD

**Issue by wzup** [kylefox/jquery-modal#175]
You have good modals, I use them in my project. However I'd like to move the project on React. Do you have (or are you aware of) a React implementation of your modals?

**Comment by kylefox** [comment]
Unfortunately I _don't_ have or know of React implementation :(

If you (or anyone else reading this thread) find a React port, please drop a comment and I'll link to it. Or, feel free to take a stab at creating a React component for it!

**Comment by ddxtanx** [comment]
I use React, and I just add jQuery into my project and am able to run this code just fine!
Importing it is just like normal,
```js
import $ from 'jquery';
import 'jquery-modal';
```
Then I can reference `$.modal` and `$().modal` wherever I want in my code.

**Comment by vikingcodes** [comment]
Hi, when we using    ($('#my-profile') as any).modal(); in ReactJs TypeScript.  Events inside JqueryModel not working. Anybody faced similar problem ?
