### ISSUE TITLE
Bower complains when used w/ jQuery 3.x

### ISSUE THREAD

**Issue by shane-tomlinson** [kylefox/jquery-modal#176]
![screen shot 2016-09-05 at 11 32 52](https://cloud.githubusercontent.com/assets/848085/18245325/81a81bda-735c-11e6-8fd4-eb6233d05a54.png)

**Comment by kylefox** [comment]
Thanks @shane-tomlinson, this should be fixed in [v0.7.2](https://github.com/kylefox/jquery-modal/tree/v0.7.2)

**Comment by shane-tomlinson** [comment]
Thanks @kylefox!
