### ISSUE TITLE
Expose current modal

### ISSUE THREAD

**Issue by ShaneTWright** [kylefox/jquery-modal#178]
I would like to be able to access the current modal without having to track the modal states independently of the state tracking within the plugin. 

This should be fairly easy to expose by adding a "getCurrent" method to $.modal which is a direct reference to the current "getCurrent" function. 
```javascript
$.modal.getCurrent = getCurrent;
```

Or, if you would rather not expose the modal instance itself you could add a "getCurrent" method to $.modal which wraps the current "getCurrent" function and return the modal instance's $elem only.
```javascript
$.modal.getCurrent = function () {
  var current = getCurrent();

  return current !== null ? current.$elem : current;
};
```
However this seems awkward as access to the $blocker and options would probably be useful as well. Also, this same result could currently be achieved with:
```javascript
function  myGetCurrent () {
  return $('.jquery-modal.blocker.current').children('.modal');
}
```

But that would get inefficient (relatively) if I needed to work through multiple, stacked modals.

**Comment by kylefox** [comment]
Thanks for the suggestion @ShaneTWright — this is now available in the 0.7.3 release.
