### ISSUE TITLE
Delay to test spinner

### ISSUE THREAD

**Issue by brakai295** [kylefox/jquery-modal#179]
Thanks so much for this handy piece of code!

I'm trying to test the spinner, but things are always loading to quickly. Is there an easy way to delay the loading of the modal window so I can test and style the spinner?

Thanks again!

**Comment by kylefox** [comment]
Hmmm, interesting point. No, there isn't a built in way to do this. You'll need to hack something together.

A few ideas for you:

* Hack `jquery.modal.js` and wrap the AJAX call within a `setTimeout` (or just comment out the code that runs when the AJAX request finishes).
* Add a delay to your server-side API endpoint which responds to the AJAX request

Another idea is to simply use the modal API to fake the state you want. So, open your AJAX modal as normal and then from the JavaScript console:

```javascript
var m = $.modal.getCurrent();
m.hide();
m.unblock();
m.showSpinner();
```

That code will close the modal, remove the overlay, and show the spinner. A bit annoying to rerun that every time you test, but it should work.

Hope this helps!

**Comment by brakai295** [comment]
Thanks Kyle! The second idea worked beautifully!
