### ISSUE TITLE
Serious confliction with bootstrap

### ISSUE THREAD

**Issue by shanewangs** [kylefox/jquery-modal#181]
Hey mate!

Looks like all methods of opening a jquery-modal involve adding "modal" class to the content to be displayed. 

This class name **"modal" is too general** and has already been used with a popular framework bootstrap, therefore when these two is used in a same page, styles overriding each other will make the actual modal terrible. 

It would be better **make class name changable** instead of "modal" all the time, such as making `<a href="#login-form" rel="specific-modal:open">Login</a>` available for class "specific-modal".

**Comment by kylefox** [comment]
Hello! Unfortunately this is a known incompatibility and is mentioned in the README:

> Naming conflict with Bootstrap: Bootstrap's modal uses the same $.modal namespace. If you want to use jquery-modal with Bootstrap, the simplest solution is to manually modify the name of this plugin.

(See also #136 and #62)

I don't really have plans to change this. Even though "modal" is very general, I like how concise it is. Sorry!

Just out of curiosity — why not use the modal included with Bootstrap? IMO it's pretty good.

Cheers!

**Comment by shanewangs** [comment]
Hey mate, 

Thanks a lot for your reply!

So I was trying to modify bootstrap modal's close button to make it more stylish and relocate it as well, then I came across this nice modal when searching for styles. It's basically what I'm looking for and definitely of less hassle to modify for my project. 

And thanks again for creating this convenient plugin!

Shane

**Comment by nsbasic** [comment]
Let me add my vote for making this configurable. The Modal library is more flexible than the Bootstrap one, and works in more cases.

When I get a new version, I do a search and replace of ".modal" to ".jqmodal" in both the js and css files as a workaround.

**Comment by EasonPai** [comment]
> Let me add my vote for making this configurable. The Modal library is more flexible than the Bootstrap one, and works in more cases.
> 
> When I get a new version, I do a search and replace of ".modal" to ".jqmodal" in both the js and css files as a workaround.

Can you share the steps how you workaround it?
All we need is rename all ".modal" in css? What exactly files we need rename?
Thanks

**Comment by Maosalas** [comment]
Hi folks. Here is the solution

First you do a "search and replace" of **modal** to **jqmodal** or any other variable name that you want. You need to replace those names on min.js, min.css files and your div class in the html file.
Here is a quick example
**Js and CSS**
`o.modal = function(t, i) {` to `o.jqmodal = function(t, i) {`
**Html**
```
<div id="ex1" class="modal">
  <p>Thanks for clicking. That felt good.</p>
  <a href="#" rel="modal:close">Close</a>
</div>
<p><a href="#ex1" rel="modal:open">Open Modal</a></p>
```
**To**
```
<div id="ex1" class="jqmodal">
  <p>Thanks for clicking. That felt good.</p>
  <a href="#" rel="jqmodal:close">Close</a>
</div>
<p><a href="#ex1" rel="jqmodal:open">Open Modal</a></p>
```

**Comment by dextar47** [comment]
There is another solution to just unbind previous click events specifically on your modal trigger button and then it worked at myside.
