### ISSUE TITLE
data-modal not opening

### ISSUE THREAD

**Issue by Isengo1989** [kylefox/jquery-modal#183]
When I am trying to open a link/picture with the data-modal / ajax option it does not work.

`<a href="www.test.de/img.jpg" data-modal>Open an AJAX modal</a>`

```
$('a[data-modal]').click(function(event) {
            $(this).modal();
            return false;
        });
```

No errors in my JS console and jQuery and Script are inserted. Any ideas?

**Comment by kylefox** [comment]
Hmmm, that _looks_ correct. Can you link to a publicly-accessible page that demonstrates the problem?

**Comment by emkae** [comment]
[This is wrong](https://pwny.emkae.net/#!/?s=html&c=9&l=4&t=5d00000002bf01000000000000001e1cc86755bb63d868551718ad8cbae957433adc0f6afa4a15a0ffa881ce6495bddea1d0149519ff7acef25a95954195caa0fce29a5c2fb60bd809a73bf7932eecb48a935e5b7e8f5bbaf260ccfa6b0ec93e713479aaaf2c47b7f3e236a0c9b9f60bd7d8177a77d5c247a2ab13d20febc7ca6507228eccae0cd5ac653d9191647c5b62ca44e82a04dad33d88855cff077493a8f1c0bed214c13b6efba330ddc73a15f8d250574df1b1cc39e3ceb3b9dd5e98e78e1e4a2c0ae835587a5150072ca9b6f0415f7d21f31a461278e1cde65b23f20841f73026d23842ad6df7c7d392d81b854c7464be945f43fab2e20b6f0ab28f3c6a43118242212348ac87328b7c3083ef7cbeaa84ffd4747420) and [this works](https://pwny.emkae.net/#!/?s=html&c=9&l=4&t=5d00000002c701000000000000001e1cc86755bb63d868551718ad8cbae957433adc0f6afa4a15a0ffa881ce6495bddea1d0149519ff7acef25a95954195caa0fce29a5c2fb60bd809a73bf7932eecb48a935e5b7e8f5bbaf260ccfa6b0ec93e713479aaaf2c47b7f3e236a0c9b9f60bd7d8177a77d5c247a2ab13d20febc7ca655651869a67797df90c0d89ba66eef09ed7861e2e26a6d297b80c9c9a540f0337292002335ee2e0321ff95b5e246a97d669c1c7deb2bc7142a0d73ddb62a0e429d81448ce40a3d675bd7a41234bb46ad106982b7aa9482b7bdd1aff39485c9e0ea75529b336ab9d621e05bb836bdb415a8dc5fc66159c8c8966654faab9ff5902c03e231076734bc334964620136cf7008d403787ff99367000).

Wrong:
`www.test.de/img.jpg`

Right:
`https://www.test.de/img.jpg`

Besides, you might throw CORS exceptions when doing `$(this).modal()`, so to work around that I find `$("<img src=" + this.href + " />").modal();` more robust :)
