### ISSUE TITLE
Detect close event targer

### ISSUE THREAD

**Issue by alekciy** [kylefox/jquery-modal#184]
How I can detect "_popup was closed by the close button_", "_popup was closed by the overlay_", "_popup was closed by the Esc button_"?

Now this is impossible, right?

**Comment by kylefox** [comment]
That's right, currently this functionality is not built in.

However if you wish to add it, it's probably relatively simple. You could to pass something like `{ closeMethod: 'esc' }` or perhaps `{ closeMethod: $element }` to the `close()` and `hide()` methods where necessary and add that data to the event context.

I'm not able to add this functionality myself, but feel free to create a form 😄  I would also consider a pull request, but it would require more discussion around how the public API would work first.

(Have a look at the [contributing guidelines](https://github.com/kylefox/jquery-modal#how-to-contribute) if you're interested in submitting a pull request).
