### ISSUE TITLE
Smoother transition

### ISSUE THREAD

**Issue by cyphix333** [kylefox/jquery-modal#185]
Hi there and thanks for the simple modal plugin.

From what I can tell you are using JS for the transition at the moment? Just a suggestion to move over to using CSS to make the transition smoother - I have noticed at some longer transitions it can be quite jagged/laggy.

You could simply use opacity from 0% to 100% easily enough no!?

**Comment by kylefox** [comment]
I agree that CSS animations would be a great improvement, and are part of the [Proposal for jQuery Modal 2.0](https://github.com/kylefox/jquery-modal/issues/169) — pull requests welcome 👍 

(The README has some information about [contributing](https://github.com/kylefox/jquery-modal#contributing)).
