### ISSUE TITLE
modal not opening with error Unable to get property 'children' of undefined or null reference

### ISSUE THREAD

**Issue by ychen2k** [kylefox/jquery-modal#188]
I am getting an error with the script: Unable to get property 'children' of undefined or null reference on line 127.  any suggestions?  thanks

**Comment by Ismail06** [comment]
Check you code. May be in modal form you use id="#id" instead id="id" ;)

**Comment by kylefox** [comment]
Hi, if this is still an issue please submit a publicly-accessible test case so we can troubleshoot further. Thanks!

**Comment by shanemac10** [comment]
If anyone else is experiencing this error, double check the `href` attribute in the link is pointing to the `id` on the modal properly.

`<a href="#my-modal-id" rel="modal:open" ... >`
`<div id="my-modal-id" style="display:none;">`
