### ISSUE TITLE
X not rendering completely

### ISSUE THREAD

**Issue by jacobo360** [kylefox/jquery-modal#189]
Hi,

As you can see in the attached picture, the circled x is not rendering correctly. Is there a way to correct this or a reason why this might be happening?

![screen shot 2016-10-31 at 11 02 33 pm](https://cloud.githubusercontent.com/assets/17790597/19878436/d052032a-9fbe-11e6-8cfd-3cc17cc48a28.png)

**Comment by fronchetti** [comment]
Same problem here
![captura de tela de 2016-11-05 13 42 22](https://cloud.githubusercontent.com/assets/15092904/20031394/d8e3221a-a35d-11e6-8575-c029ba673eb6.png)

**Comment by fronchetti** [comment]
Same problem here
![captura de tela de 2016-11-05 13 44 20](https://cloud.githubusercontent.com/assets/15092904/20031408/16ab14f4-a35e-11e6-9ed9-824ba894a365.png)

**Comment by Quilmont** [comment]
I was having this issue as well. I fixed it by adding overflow-y:visible; to the CSS under .modal. I hope this helps.

**Comment by kylefox** [comment]
I just tried the [examples](http://jquerymodal.com/) in Chrome / Safari / Firefox and was not able to reproduce this issue. To troubleshoot further:

1. In which browser(s) did you observe the problem?
2. Are you using the latest version (0.8.0) of the library?
3. Are you using any other libraries, widgets, frameworks, etc. which may be interfering with the modal?

It _seems_ that CSS from somewhere is applying an `overflow` rule to the `.modal` that is causing the close button to appear clipped. My guess is another library.

If you provide the information above as well as a publicly-accessible test case, I can re-open and have a closer look.

And of course, if you found the solution — please share! 😁

**Comment by kylefox** [comment]
After investigating further I'm nearly certain the issue is due to Bootstrap, which specifies  `.modal { overflow: hidden; }`

**Comment by codewordmd** [comment]
On a more general level, there seems to be numerous conflicts between this plugin and Bootstrap because of their own modal jquery functionality and associated classes in their framework's stylesheets. I installed local copies of your .js and .css files and just replaced all instances of "modal" with "modal_popup" in both files, and now it works perfectly. Much easier than trying to override Bootstrap.

**Comment by logofun** [comment]
> On a more general level, there seems to be numerous conflicts between this plugin and Bootstrap because of their own modal jquery functionality and associated classes in their framework's stylesheets. I installed local copies of your .js and .css files and just replaced all instances of "modal" with "modal_popup" in both files, and now it works perfectly. Much easier than trying to override Bootstrap.

good idea
