### ISSUE TITLE
Can we use button to open modal?

### ISSUE THREAD

**Issue by jasonwzhu** [kylefox/jquery-modal#191]
Thanks for the great library!

Just wondering if possible to use a button instead of a href link to open the modal?

If yes, how?

Best Regards,
Jason

**Comment by Quilmont** [comment]
Not sure if this is the proper way to do this, but the easiest way (and it worked for me) is just to set the anchor to the modal window around your button like so:

`<a href="#ex1" rel="modal:open"><button>Edit </button></a>`
Hope this helps!

**Comment by kylefox** [comment]
That approach works, or you could simply [open the modal manually](https://github.com/kylefox/jquery-modal#method-2-manually) with custom event handlers.

```javascript
// Attach to buttons that have a `data-modal` attribute.
$('button[data-modal]').click(function(event) {

  // Get the related target, ex: "#my-modal" (will be a string/selector)
  var modal = $(this).data('modal');

  // Get that element from the DOM and open the modal.
  $(modal).modal();

  return false;
});
```

You can then use buttons to open modals like so:

```html
<button data-modal="#my-modal">Open Modal</button>
```

This is similar to how the automatic-open behavior of links works.

_(Note this code is untested, but this idea general idea should work)._

**Comment by jasonwzhu** [comment]
Thank you so much for your help.

best regards,
Jason

**Comment by ssuess** [comment]
Hm, when I try your above code, jquery throws an error:

`Syntax error, unrecognized expression: https%3A%2F%2Fmy.url.com%2Fdatacall.php`

any ideas?

**Comment by kylefox** [comment]
It is impossible to debug without having access to the page, sorry.

**Comment by ssuess** [comment]
no worries, I worked around it by wrapping the button in the a tags instead.
