### ISSUE TITLE
Close button cut off in modal

### ISSUE THREAD

**Issue by edwinokugbo** [kylefox/jquery-modal#192]
I have added the modal to my project but this is what I get when i call the modal.

The close button is cut off. Is this a bug or am I doing something wrong?

Cheers

![modal2](https://cloud.githubusercontent.com/assets/13503875/20765369/4fa8ac98-b732-11e6-9881-ecc1b9cb911e.png)

**Comment by kylefox** [comment]
My guess is you're Bootstrap — have a look at #189 and see if that helps 😸

**Comment by leandrocastro** [comment]
.modal {
  overflow: initial;
}

**Comment by logofun** [comment]
@leandrocastro 
good idea 
it solve the problem of mine

**Comment by shravankumar9892** [comment]
> .modal {
> overflow: initial;
> }

Thank you so much !

**Comment by aualdrich** [comment]
Worked for me as well. Thanks!
