### ISSUE TITLE
Conflict with bootstrap.css 

### ISSUE THREAD

**Issue by MurKit** [kylefox/jquery-modal#194]
If this plugin is used with a Bootstrap, modal looks like this. And I cannot figure out how to fix it. 
![screenshot from 2017-01-04 12 27 28](https://cloud.githubusercontent.com/assets/13369896/21639561/686871fc-d279-11e6-8d74-9155d2588df2.png)

**Comment by MurKit** [comment]
Oh, I have figured it out, is was because of overflow: hidden.

**Comment by kylefox** [comment]
Yep, likely the same as #189.
