### ISSUE TITLE
Please support url link for image and support iframe.

### ISSUE THREAD

**Issue by korenevskiy** [kylefox/jquery-modal#195]
Please support functions as "SqueezeBox". 
1. Open modal windows with image from url "< a href='img/image.jpg'>modal image< / a>"
2. Open modal windows with site in <iframe/> from url "< a href='domain.com/' >modal site in iframe< / a >"
.
Example: https://www.spiralscripts.co.uk/Joomla-Tips/using-modal-windows-with-joomla.html

**Comment by emkae** [comment]
I don't know, but this seems like an overkill to me. Basically it already supports what you want:

HTML

```html
<a href="https://emkae.net/pump.jpg" data-fooimg>Click for a Image</a>
```
JavaScript

```javascript
var fooimg = function(evt) {
	evt.preventDefault();
	var url = this.href;
	$('<img src="'+url+'" />').appendTo('body').modal();
};
$('[data-fooimg]').on('click', fooimg);

```
With some basic programming knowledge you can implement the same for your iframe stuff!

**Comment by tmuka** [comment]
thanks, this solution worked for me!  It might be a nice addition to the project readme.
