### ISSUE TITLE
Handle back button on Android devices

### ISSUE THREAD

**Issue by efares** [kylefox/jquery-modal#197]
Hi,

This works great on my website but when the modal is opened and viewed on an Android device and then the user taps their back button, the mobile browser leaves/closes the website.

To reproduce, open jquery-modal on an Android phone and then tap the back button.
Is there any way the back button can just close the modal?

Thanks!

**Comment by emkae** [comment]
That is how browsers work, when the URL does not change, when you open the modal window, it will call `history.back()`.

You can work around that, by doing something like this:

HTML
```html
<button>Click to view the video</button>
```

JavaScript
```javascript
(function(window, document){
$(window).on('popstate', function() {
  if(window.location.hash === '#kylefoxrocks') {
    $('.jquery-modal').remove();
  }
});
$('button').on('click', function(evt) {
	evt.preventDefault();
	window.location.href = '#kylefoxrocks'
	window.location.href = '#modalopened'
	var video = document.createElement('video');
	var src = document.createElement('source');
	video.setAttribute('controls', '');
	src.setAttribute('src', 'https://cdn.emkae.net/magic-mike-xxl-i-want-it-that-way.mp4');
	src.setAttribute('type', 'video/mp4');
	video.appendChild(src);
	$(video).appendTo('body').modal();
});
})(window, document);
```

See the [Demo](https://pwny.emkae.net/#!/?s=html&c=21&l=18&t=5d000000028603000000000000001e1cc86755bb63d868551718ad8cbae957433adc0f6afa4a15a0ffa881ce6495bddea1d0149519ff7acef25a95954195caa0fce29a5c2fb60bd809a73bf7932eecb48a935e5b7e8f5bbaf260ccfa6b0ec93e713479aaaf2c47b7f3e236a0c9b9f60bd7d8177a77d5c247a2ab13d20febc7ca681ac5449dd1c4d4ea85e17e56626c531b6357aaab20146976639dddf064f9e229dda6f733a6342d1de88b945ea068c51dc2104c00e74b021667b6686aec173b47db5053b10768c7e14ea7bdfb584bb629425cfd34fcda5c028438fa47c38ecf115b5ca939e502ea5a6ad49452231f091a67470e368d86d91f46a7ace450ae1aef71ab0a5a569cd5e4ea96a3921819785f5fb2e905b4fd332b642e4bedb1ad3974fd2a8bb596b947c847e9fe9247559b28e9f1002f8b94b09fd8a2a6fe3d3431572427f937fee917b29c3f62529f997b20c9262be9cb8a042f767a4b0d2e7ffd4b6076b1898c4416eda100db06e604622fd47e71b318462043f5dd236457f6f72d6c04a10c5d895347696ea85b56738fcf2eefd51837c9d0ccd22d5239c0961a3e0d1d5809dcfe0aa21a77632534fffcf84954e925a825fe6eff09cc0c56e1c6b6a8fda5cd1ce857c3fa1de764142f0a33f2086f60f614f62a4c70d06243ffbf2b9ea9&a=1)
[Demo Source Code](https://pwny.emkae.net/#!/?s=html&c=21&l=18&t=5d000000028603000000000000001e1cc86755bb63d868551718ad8cbae957433adc0f6afa4a15a0ffa881ce6495bddea1d0149519ff7acef25a95954195caa0fce29a5c2fb60bd809a73bf7932eecb48a935e5b7e8f5bbaf260ccfa6b0ec93e713479aaaf2c47b7f3e236a0c9b9f60bd7d8177a77d5c247a2ab13d20febc7ca681ac5449dd1c4d4ea85e17e56626c531b6357aaab20146976639dddf064f9e229dda6f733a6342d1de88b945ea068c51dc2104c00e74b021667b6686aec173b47db5053b10768c7e14ea7bdfb584bb629425cfd34fcda5c028438fa47c38ecf115b5ca939e502ea5a6ad49452231f091a67470e368d86d91f46a7ace450ae1aef71ab0a5a569cd5e4ea96a3921819785f5fb2e905b4fd332b642e4bedb1ad3974fd2a8bb596b947c847e9fe9247559b28e9f1002f8b94b09fd8a2a6fe3d3431572427f937fee917b29c3f62529f997b20c9262be9cb8a042f767a4b0d2e7ffd4b6076b1898c4416eda100db06e604622fd47e71b318462043f5dd236457f6f72d6c04a10c5d895347696ea85b56738fcf2eefd51837c9d0ccd22d5239c0961a3e0d1d5809dcfe0aa21a77632534fffcf84954e925a825fe6eff09cc0c56e1c6b6a8fda5cd1ce857c3fa1de764142f0a33f2086f60f614f62a4c70d06243ffbf2b9ea9)

**Comment by Gillesvk** [comment]
I have the same issue using Kyle Fox modal in my single page website where I load external content in full screen modal. The user leaves website when he taps browser back button instead of modal close button. 

I try to resolving it by manipulating the history API with Jquery. 
In the example code bellow, "window.history.pushstate" and "window.history.back" methods works well when I click the modal open and close button, but I can't figure out how to handle browser back and forward button to make modal reopen on forward and close on back. It's something to do with "popstate". 

Any help ?

Here is an example code:

Index page:

`<a href="ajax-content.html" data-modal>Load ajax content</a>`


Content load in modal (ajax-content.html):
```
<p>I'm ajax content.</p>
<a href="#" id="closemodal">Close</a>
```


Jquery:
```
<script>

// Open modal and history pushstate
$('a[data-modal]').click(function(event) {
    $(this).modal();
    window.history.pushState(null, null, this.href);
    return false;
});

// Close modal and history back
$("body").on('click', '#closemodal', function () {
    $.modal.close();
    window.history.back();
    return false;
});

// Browser back and forward button   
$(window).on('popstate', function () {
    ... ???
});

</script>
```
 Any help would be most welcome ?
