### ISSUE TITLE
How to handle AJAX forms?

### ISSUE THREAD

**Issue by dan-passaro** [kylefox/jquery-modal#199]
So I had a great time rendering a simple form on the server side and getting it to popup as a modal using this plugin, the entire process was so painless I was pretty impressed!

The only issue.. When the user submits, it doesn't work properly.  I understand why on a technical level, however it seems odd to me that I have to write some glue code to get the form submissions to work. The examples include a login form but it seems like the full story of that form isn't explained.

Is there any support for this case?  I'm not sure what the "best practice" is... for now I'm rendering the form/form with errors server side and doing a simple content replace, unless the form submit was a success, in which case the server returns a special JSON response that includes a redirect URL, and the client side event handler checks for that response and updates window.location appropriately.

I feel like I've written a bit of a mess, but I don't know the simplest possible way of doing what I'm trying to do (namely making a popup form that redirects the entire browser on success, presumably somewhat similar to the demo login popup).

Is there any document that describes a straightforward strategy for implementing AJAX forms with this plugin?  Is there any interest in perhaps providing an opinionated but optional 'happy path' for making implementing forms in this manner more obvious?

**Comment by emkae** [comment]
I feel like closing this issue, because it's unrelated to the plugin. This plugin does one thing and does it pretty well. It shows a modal overlay. If you're struggling with AJAX and forms, that's a different story.

**Comment by dan-passaro** [comment]
From a code point of view, perhaps you're right and this is unrelated to the plugin, but from the point of view of the actual use case of this plugin, it seems pretty relevant.  If people are creating modals I'm sure many of them include text fields.  The project's own README includes a login example with inputs where the issue of "what happens when they click submit" isn't discussed.

Just a little extra documentation here to explain what might actually happen in a web app would be an improvement.  This doesn't necessarily need any new code.

**Comment by kylefox** [comment]
Form submission handling is definitely outside the functional scope of this plugin. I'd argue that it's even outside the scope of _documentation_ — there are infinitely many ways someone might want to handle form submissions.

You could, for example, use a plugin like [jquery-form](https://github.com/jquery-form/form) to wire up a form that submits via AJAX, and then closes the modal when complete:

```javascript
$('#login-form').ajaxForm(function() { 
  $.modal.close();
});
```

If you're trying to do this

> a popup form that redirects the entire browser on success

you don't even need AJAX. Just make the form a plain old HTML form and have your server return a redirect when it's submitted.
