### ISSUE TITLE
Prevent removing from DOM

### ISSUE THREAD

**Issue by elemashine** [kylefox/jquery-modal#201]
Hello! I use more than one modal with
`$(this).parent().find('.modal').modal();`
And after opening modal, this div dissapearing. How can I prevent this? Thanks

**Comment by emkae** [comment]
Via configuration?

```javascript
$.modal.defaults = {
  closeExisting: true    // Close existing modals. Set this to false if you need to stack multiple modal instances.
};
```
Source: [https://github.com/kylefox/jquery-modal#options](https://github.com/kylefox/jquery-modal#options)

**Comment by kylefox** [comment]
Yup, what @emkae suggests is correct.

Please see [Example 6: Multiple Modals](http://jquerymodal.com/#example-6) for a demonstration of how `closeExisting: false` works.
