### ISSUE TITLE
Firefox issue on PC 

### ISSUE THREAD

**Issue by aosipov** [kylefox/jquery-modal#202]
When you closing the modal window with the video in Firefox on PC, audio still playing...

**Comment by emkae** [comment]
That's not an issue with Firefox, the other browsers should handle it the same way (it's actually in every other Browser that does not continue to play the video-file, even if I like Chrome the best ;))

You need to take care of pausing the video like so:

HTML
```html
<button>Click to view the video</button>
```
Javascript
```javascript
(function(window, document){
$('button').on('click', function(evt) {
  var video, src, $modal;
	evt.preventDefault();
	video = document.createElement('video');
	src = document.createElement('source');
	video.setAttribute('controls', '');
	src.setAttribute('src', 'https://cdn.emkae.net/magic-mike-xxl-i-want-it-that-way.mp4');
	src.setAttribute('type', 'video/mp4');
	video.appendChild(src);
	$modal = $(video).appendTo('body').modal();
  $modal.on($.modal.BEFORE_CLOSE, function(event, modal) {
    video.pause();
    // or $modal.remove();
    // if you do not need the modal anymore..
  });
});
})(window, document);
```

See the [Demo](https://pwny.emkae.net/#!/?s=html&c=0&l=21&t=5d000000026f03000000000000001e1cc86755bb63d868551718ad8cbae957433adc0f6afa4a15a0ffa881ce6495bddea1d0149519ff7acef25a95954195caa0fce29a5c2fb60bd809a73bf7932eecb48a935e5b7e8f5bbaf260ccfa6b0ec93e713479aaaf2c47b7f3e236a0c9b9f60bd7d8177a77d5c247a2ab13d20febc7ca681ac5449dd1c4d4ea85e17e56626c531b6357aaab20146976639dddf064f9e229dda6f733a6342d1de88b945ea068c51dc2104c00e74aef37eaa38c4ec74048bc0eaa7bdf4574bfcd90a7593bb025d4245c10c81c1882416de80250ac48b255260df0a7d2e2dc725614e5c8517365a91ff4633ba2588f32e3b4d567de96612a4c5d622707e0f8ce0b082383a4e6fc59f54dcfeaa4872c6702a5a9323c7c0166c1ee76e08b3e0a004fe0cd45dd51d82e72c3bc2856631d16e66e9ed4767b51e429f077c9cb434d36a9106e0865ec7dcdcc20d67423a6320253894bf0e0ee23bbb7abf79ddc4f9f828dd10ed3ac27d41c9ed3389c95edaf6bd194ef39957b1c4a73f461cf4fc175a43d7d2eb615e25cd5575ba27facf456af8b73f17f9a9922154a59c1e135e5405790b772ed23a266aaa00cf7e17efc571bcca542b32673b4237964b5b0b6372ee3acb4d9f4da9cb0200762a8ac330ee82a580c3b7f994ea824c8ffe8ac8d6c) (Menu -> Run / CTRL + Enter)
