### ISSUE TITLE
Get Ajax target url from event

### ISSUE THREAD

**Issue by eavilesmejia** [kylefox/jquery-modal#203]
I'd like to have something like this:

```
function log_modal_event(event, modal) {
      if (event.type == $.modal.OPEN) {
          window.history.replaceState('Object', 'Title', event.AJAXURL);
      }

      if (event.type == $.modal.CLOSE) {
          window.history.replaceState('Object', 'Title', event.currentTarget.baseURI);
      }
}
 $(document).on($.modal.OPEN, log_modal_event);
 $(document).on($.modal.CLOSE, log_modal_event);
```
is it currently possible?

**Comment by emkae** [comment]
Yep, seems possible to me:

HTML
```
<a href="/assets/pwny.css" rel="modal:open" data-modal-links>Inception</a>
```

JavaScript
```javascript
(function(window, document){
  (function($){
    $.event.special.destroyed = {
      remove: function(o) {
        if (o.handler) {
          o.handler()
        }
      }
    }
  })(jQuery);
var onAjaxModalCloseCallback = function(evt) {
  alert('close');
  //window.history.replaceState('Object', 'Title', url.href);
};
var onAjaxModalCompleteCallback = function(evt) {
  console.log($(".jquery-modal").length);
  $(".jquery-modal").on('destroyed', onAjaxModalCloseCallback);
  // var target = evt.target;
  // var url = new URL(target.href);
  if (evt.type == $.modal.AJAX_COMPLETE) {
    alert('open');
    // window.history.replaceState('Object', 'Title', url.pathname);
  }
};
$('[data-modal-links]').on($.modal.AJAX_COMPLETE, onAjaxModalCompleteCallback);
})(window, document);
```

See [Demo](https://pwny.emkae.net/#!/?s=html&c=0&l=6&t=5d000000023604000000000000001e1cc86755bb63d868551718ad8cbae957433adc0f6afa4a15a0ffa881ce6495bddea1d0149519ff7acef25a95954195caa0fce29a5c2fb60bd809a73bf7932eecb48a935e5b7e8f5bbaf260ccfa6b0ec93e713479aaaf2c47b7f3e236a0c9b9f60bd7d8177a77d5c247a2ab13d20febc7ca65071e16152f93a7aff7078bd1c98c628ac8b7811685f3564e499e7e1ab7565c0d0ffc33240e77878a1aa01de461a9144422c4ce63f7052c32ed64a48a28fbbaed76a9fe13fec3681668b013d93f5665bea8ce499ba54dfeb24500bf1c5d832c079db77b3399c338cfbc893d9a3c625083d9447250a84eb7033dcfca11e55dfd20a944e2c4f74d1441a3ba38258f69bec8de002d737495ee1a91c68d06b6894565c102bfcffec24ef02716d7bc540f761548f69674b86aa51aae8af5756f5c3060dfa22819fe8912252360cecbc0292ebc59033445fb167d5ef30051f5aab1c94552346bba049cb704f17a6174e2e89d50a25d5a6e1cf38eef684c2258fb8043352e981403224d47ae15735f908959a9acb2f5c80ba8b22b62b649fd4a01076da406c5257e7e4b10137d8b9bc3675705a911fc111b510a88dbb96b40bae2d5d3fe0e2ce7d8df823b909bbc44521ae6a1083d0654d6031887fa1c9fca15299e651bab1bf4a743a9f26555746a997e02d4da874bf7eab6f068a76e45889e846cb1983d5796ce8b0ecafa2a7e86fdf896ef5cfff0843c95)

**Comment by eavilesmejia** [comment]
Nice!! thanks a lot @emkae, it works :)
