### ISSUE TITLE
Set width through options

### ISSUE THREAD

**Issue by unlikenesses** [kylefox/jquery-modal#204]
It would be good to be able to set the modal width through options. Currently I'm setting it in the CSS for `.modal` but if I want two modals to have two different widths that's not useful.

**Comment by kylefox** [comment]
You could probably implement this fairly easily using a custom `data-*` attribute and the `$.modal.BEFORE_OPEN` event.

This is just an example — I haven't tried this code, but hopefully it gives you the general idea of the approach. Note the `data-modal-width` attribute:
```html
<!-- wide modal -->
<div class="modal" data-modal-width="600"></div>

<!-- narrow modal -->
<div class="modal" data-modal-width="200"></div>

<script>
  $(function() {
    // Apply fixed width to modals that have a `data-modal-width` attribute
    $(document).on($.modal.BEFORE_OPEN, '.modal[data-modal-width]', function(event, modal) {
      modal.elm.css('width', modal.elm.data().modalWidth);
    });
  });
</script>
```

**Note:** You'll also need to remove any `max-width` or `min-width` applied to `.modal`

Hope this helps.
