### ISSUE TITLE
Conflicts with bootstrap css framework

### ISSUE THREAD

**Issue by nanofelix** [kylefox/jquery-modal#217]
For example bootstrap.css contains .modal class which mixes with jquery-modal's .modal class.
The same thing with boostrap.js, if i move bootstrap's js link in html code above jq modal's js link, jquery modal starts working, otherwise it doesnt. Never use widespread class names and names of js functions.

**Comment by kylefox** [comment]
Yep, this is a [known issue](https://github.com/kylefox/jquery-modal#installation). Compatibility with Bootstrap is not planned. Your best option is to rename `jquery-modal` locally, or use Bootstrap's built-in modal.

**Comment by hussainabidbest** [comment]
if we want to user with bootstrap, can anybody help like how to rename to jquery-modal and where should we do?

**Comment by EasonPai** [comment]
Yap, would like to know too. How to jquery-modal to work with bootstrap?
