### ISSUE TITLE
Add another function on closing

### ISSUE THREAD

**Issue by nevonevo** [kylefox/jquery-modal#219]
hi there. i wanna learn can we add some new function while modal closing. For example i want to add a form on modal, and when click the submit button i wan to send form values and close the modal. Is it possible?

**Comment by kylefox** [comment]
What you probably want to do it submit the form with [AJAX](https://api.jquery.com/jQuery.ajax/) (out of scope for this plugin) and then manually close the modal using `$.modal.close();` in the success callback. 

Something like: 

```javascript
$('#my-form').on('submit', function() {
  $.ajax({

    // ... your AJAX configuration goes here ...
    
    success: function() {
      $.modal.close();  // <= close after AJAX call succeeds
    }
  });

  return false;
});
```

If this isn't exactly what you need, you can close them modal at any time using `$.modal.close();`. You can refer to the README for more information about [Closing](https://github.com/kylefox/jquery-modal#closing) and [Events](https://github.com/kylefox/jquery-modal#events), which might also be helpful.

**Comment by nevonevo** [comment]
thanks for your fast reply. This worked for me.

**Comment by marcbarry** [comment]
please can you add this `$.modal.close();` to the documentation on https://jquerymodal.com/ ? :)
