### ISSUE TITLE
Passing data attiribute into the modal

### ISSUE THREAD

**Issue by nevonevo** [kylefox/jquery-modal#220]
Hi there, i have an issue about the passing data into modal. 

I append this div into my project by another simple button.

`var $element = $('<div class=\"table dort_yatay ui-draggable destroy'+table_random_number+'\" id=\"table_draggable\" data-table_random=\"'+table_random_number+'\" data-need=\"'+table_number+'\"><span class=\"dort_yatay_table_vertical_align\">M '+table_number+'</br><a href=\"#ex3\" rel=\"modal:open\" class=\"link_passive table_update_link destroylink'+table_random_number+'\" id=\"masa_duzenle_link\" data-table_randomss=\"'+table_random_number+'\"></a></span></div>');`

And as you can see there is a data attribute in a tag which name is "ata-table_randomss".

I tried to pass this data into modal but i couldn't. 

```
	$("#masa_duzenle_link").click(function(event, ui){
		var table_random_numbers_modal = ui.helper.data("table_randomss");
		console.log(table_random_numbers_modal);
		alert(table_random_numbers_modal);
	});
```
i used these codes to get data but my a tag click function is open modal only and i can not use another function when modal is opening. So do you know how can i pass data into modal?

PS: i append many div in the same method. So i have to get specific data according to appended divs.

Thanks.

**Comment by kylefox** [comment]
Please link to a publicly-available test page that demonstrates your issue. If you can do that I'll re-open. Thanks.
