### ISSUE TITLE
modal window inside another div

### ISSUE THREAD

**Issue by mafar** [kylefox/jquery-modal#221]
I need the modal window (including the gray background) to be applied on a div from the website and not on the body

Similar question and solution for bootstrap modal here
https://stackoverflow.com/questions/21555585/bootstrap-modal-window-inside-another-div

another bootstrap solution https://webkul.com/blog/how-to-display-a-bootstrap-modal-inside-a-div/

**Comment by kylefox** [comment]
Placing the modal within an element other than `<body>` is outside the scope of this plugin, sorry.

Your best bet might be to modify the plugin and allow a parameter to be passed in and used as the internal [`$body`](https://github.com/kylefox/jquery-modal/blob/master/jquery.modal.js#L34) reference. You'll also need to adjust the CSS.

Another approach could be to use [Events](https://github.com/kylefox/jquery-modal#events) to programmatically move the modal around in the DOM.

Good luck!
