### ISSUE TITLE
How to load remote URl from data-remote instead of href?

### ISSUE THREAD

**Issue by eendaworks** [kylefox/jquery-modal#222]
Anyone has get this script works loading data-remote instead of href? I need hide the URl.. Thank you!

**Comment by kylefox** [comment]
See [More advanced AJAX handling
](https://github.com/kylefox/jquery-modal#more-advanced-ajax-handling) in the README. You should be able to replace

```javascript
url: $(this).attr('href'),
```

with something like

```javascript
url: $(this).data('remote'),
```

**Comment by eendaworks** [comment]
Its true, @kylefox! Thanks for your quicky reply. I will try.

**Comment by vanboom** [comment]
Another suggestion... allow jquery.modal to pick up the href from an attribute...

Around line 43 of jquery.modal.js

```javascript
      target = el.attr('data-href');
      target = (target === undefined) ? el.attr('href') : target;
```

I would be happy to submit a PR if this would be considered a reasonable solution.  In my application I do not want the user to open modals in a new browser tab, so I put "javascript:void(0)" in the href, and put the real href in the data-href attribute.  It works perfectly.
