### ISSUE TITLE
call and open modal by function

### ISSUE THREAD

**Issue by codex7** [kylefox/jquery-modal#225]
can open modal by function?
```
function showIp(url, userId)
    {
      //event.preventDefault();
      //this.blur(); // Manually remove focus from clicked link.
      $.get(url, function(html) {
        $(html).appendTo('body').modal();

      });
    }
```

i need pass data through "onClick" and get result via "ajax"(i wrote this but not worked):
`<a href="#" id="showIp" onClick="showIp('url.html', 1)">test</a>`

please help

**Comment by walialu** [comment]
Can you try this, please?

```javascript
function showIp(url, userId) {
        $.get(url, function(html) {
                $('<div/>').append(html).appendTo('body').modal();
        });
}
```

See [demo link](https://pwny.walialu.com/#!/?s=html&c=33&l=13&t=5d000000022402000000000000001e1cc86755bb63d868551718ad8cbae957433adc0f6afa4a15a0ffa881ce6495bddea1d0149519ff7acef25a95954195caa0fce29a5c2fb60bd809a73bf79335c487d34ddf0f75fc19ebe338681e074f5d434c99a7f23b9e3c0ac4853a5985a71da037816c98d6921ce005f3a8c56c39ed54ebcaed62b147a1f5b7265334ba23eb21b25fa6705f65923ce23e53682b2fd7170d8f4b38f24628774c9954d2c1a380ebee07de3f63f4505d5ff2927af9c7e083c1bce8322147ca7a1a1166833c48c7c3d4111c9e50a5c306229828e3e792295dc0dda41edf436e705dd43f52f0462ee1d73d04c910d4848c151e7635388421d603cc03ae66cbe0b000dff8144c68ef1a1a71715e17e5477b4dfdf63420bfab8081a87e5622dd7062cd967b599a8d24e2290152d0573ffec6a2c6)

**Comment by codex7** [comment]
it's worked, but loading image is not show :(
possible write ajax sample code send and retrieve data ? i need send a data(such as userId) via post method to another page
thanks

**Comment by paweljarosz83** [comment]
So you can't just open this modal like:

$("#modalBox").modal('show');

Soooooooooooo disapoiting. Appending like you showed above is a workaround not a soultion.
