### ISSUE TITLE
process to follow when renaming addin

### ISSUE THREAD

**Issue by gjohncock** [kylefox/jquery-modal#226]
I use bootstrap on my site so looking to run this plugin so it doesnt conflict with bootstrap (i have issues with bootstrap modals not displaying elements correct, which is the reason for using this plug in.

I have replaced "modal" with "jqmodal" in many places however I have not been able to get the plugin to work.  currently I am stuck with it opening the contents of the modal in a new tab.

Do you have a guide to step through how to go about renaming the plug in correctly?

Cheers 

Greg J

**Comment by gjohncock** [comment]
issue resolved.

**Comment by EasonPai** [comment]
How do you solve this? 
Thanks
