### ISSUE TITLE
Modal opening on page load?

### ISSUE THREAD

**Issue by hopk1ns87** [kylefox/jquery-modal#228]
Not sure why this is happening, but my modal is opening on page load:
https://taylorandthomasla.com/collections/all/products/jane-blackbird

My code is:

<div id="fade" class="modal">
  <div>{% include 'size-chart' %}</div>
</div>

<p><a href="#fade" rel="modal:open">View Size Chart</a></p>

<script>
$("#fade").modal({
  fadeDuration: 100,
});
</script>

**Comment by kylefox** [comment]
Calling `.modal()` on the element will open the modal, which is what you're doing.

I assume you want the modal to open when they click the "View Size Chart" link.

In that case, you do not need to call `.modal()` at all, you can just make the link point to your modal element and add the `rel="modal:open"` attribute:

```html
<a href="#fade" rel="modal:open">View Size Chart</a>
```

(I'm assuming your modal element is something like `<div id="fade"> ... </div>`)

Please have a look at the documentation about [opening modal](https://github.com/kylefox/jquery-modal#opening) for further details.

**Comment by hopk1ns87** [comment]
Thanks for the quick reply!

I removed the .modal() call, and it seems to be working, with one exception. The opacity of the .modal class does not change from 0 to 1 when the "View Size Chart" button is clicked.

You can see what I'm referring to here: 
https://taylorandthomasla.com/collections/all/products/jane-blackbird

**Comment by hopk1ns87** [comment]
Thanks for the quick reply!
