### ISSUE TITLE
Close button text is visible with 'direction: rtl'

### ISSUE THREAD

**Issue by jlherren** [kylefox/jquery-modal#232]
The modal's close button uses `text-indent: -9999px` to hide the "Close" text while keeping the background image attached to the link. This is usually considered bad practice and does not work with `direction: rtl`, resulting in the text being visible anyway.

An alternate solution is for example proposed here: [Stop using negative left or text indents for css hiding](https://meirkriheli.com/en/2012/10/stop-negative-left-indent-css-hiding/)

**Comment by kylefox** [comment]
This project is in [maintenance mode](https://github.com/kylefox/jquery-modal/issues/170) — please submit a pull request if you'd like to see this (or any other) new functionality. Thanks.

**Comment by amirbagh75** [comment]
@jlherren add `style="text-align: right;"` to the modal div to display it correctly.
