### ISSUE TITLE
Javascript within Modal fails.

### ISSUE THREAD

**Issue by wwwmaster1** [kylefox/jquery-modal#234]
I want to make sure the content within my modal windows are not loaded independently, and if they are, I want them redirected. The redirect works great, but for some reason, the javascript prevents the modal window from displaying (the ajax calls are fine). I put this inside my html page that will be loaded into the modal...

<script>if (!(window.jQuery)){window.location.href='/';}</script>

Is there a better or correct way to do this?

**Comment by kylefox** [comment]
It's impossible to troubleshoot this without seeing the entire page's source code. Please link to a publicly-accessible page that demonstrates the problem and I can re-open this issue and investigate. Thanks!
