### ISSUE TITLE
Callback as an option?

### ISSUE THREAD

**Issue by bradley2083** [kylefox/jquery-modal#241]
It doesn't appear that there's an option to add a callback, is that right or am I just missing it in the docs?  Trying to sort out how to add an autoplay option for youtube and vimeo embeds (seems they need to be forced to autoplay for them to work properly in Chrome).

**Comment by kylefox** [comment]
Check the [Events](https://github.com/kylefox/jquery-modal#events) section of the README. There are a number of events you can bind to during the modal lifecycle. For example:

```javascript
$('#my-video-modal').on($.modal. OPEN, function(event, modal) {
  // Your code to modify modal content goes here
});
```

**Comment by bradley2083** [comment]
ah, got it.  thanks!
