### ISSUE TITLE
Modal result 2

### ISSUE THREAD

**Issue by rdisabatino97** [kylefox/jquery-modal#242]
The problem is that instead displaying data I have prepared, it shows only a 2

<img class="profile" data-image="" style="border-radius: 100%; float:right;">
        <p>Name: <span id="name"></span></p>
        <p>Surname: <span id="surname"></span></p>
        <p>Username: <span id="username"></span></p>
        <p>Email: <span id="email"></span></p>
        <p>Permission Level: <b id="permissionLevel"></b></p>

success:function(data){
                    console.log(data);
                    if(data.user.ProfilePic =="") $('.profile').initial({name:data.user.FirstName, height:64, width:64});
                    else  $('.profile').attr('src',data.user.ProfilePic);
                    $('#name').text(data.user.FirstName);
                    $("#surname").text(data.user.LastName);
                    $("#username").text(data.user.Username);
                    $("#email").text(data.user.Email);
                    switch (data.user.UserRole){
                        case '0':
                        $("#permissionLevel").text("Normal User");
                        break;
                        default:
                        $("#permissionLevel").text("Error");
                    }

                    $('#userShow').modal($e=>{
                        e.preventDefault();
                    });

**Comment by kylefox** [comment]
Hello, in order to troubleshoot this you'll need to link to a publicly-accessible page that demonstrates the problem. Thanks!
