### ISSUE TITLE
Prevent Closing Modal When Clicking Outside

### ISSUE THREAD

**Issue by ccasalicchio** [kylefox/jquery-modal#248]
How do I disable closing the modal when the user clicks outside the modal?

**Comment by kylefox** [comment]
Set `clickClose: false` as described in the readme: https://github.com/kylefox/jquery-modal/blob/master/README.md#options

**Comment by ccasalicchio** [comment]
Yes, but that removes the default close button from the modal. I'd suggest adding to the documentation that if `clickClose `is used, then a custom close button will have to be implemented

like 
`<div class="top-wrap--popup"><span class="custom-close">X</span></div>`

```
$('.custom-close').click(function () {
    $.modal.close();
});
```

Seems simple enough, but it was confusing for me to figure out that clickClose disables outside clicking, but it also removes the close button.

**Comment by kylefox** [comment]
Just to confirm, are you also setting `showClose: false`?

Disabling `clickClose` shouldn’t remove the close icon — that behavior is controlled by `showClose`

However if you’re seeing the close button disappear and you’re _not_ setting `showClose: false`, then it sounds like a bug. In which case, a publicly-visible page demonstrating the bug would be helpful 👍

**Comment by ccasalicchio** [comment]
My original code was only this
```
$.modal.defaults = {
    closeExisting: true,
    clickClose: false
};
```
From the documentation, it said the default value for showClose is true
https://github.com/kylefox/jquery-modal

```
$.modal.defaults = {
  closeExisting: true,    // Close existing modals. Set this to false if you need to stack multiple modal instances.
  escapeClose: true,      // Allows the user to close the modal by pressing `ESC`
  clickClose: true,       // Allows the user to close the modal by clicking the overlay
  closeText: 'Close',     // Text content for the close <a> tag.
  closeClass: '',         // Add additional class(es) to the close <a> tag.
  showClose: true,        // Shows a (X) icon/link in the top-right corner
  modalClass: "modal",    // CSS class added to the element being displayed in the modal.
  blockerClass: "modal",  // CSS class added to the overlay (blocker).

  // HTML appended to the default spinner during AJAX requests.
  spinnerHtml: '<div class="rect1"></div><div class="rect2"></div><div class="rect3"></div><div class="rect4"></div>',

  showSpinner: true,      // Enable/disable the default spinner during AJAX requests.
  fadeDuration: null,     // Number of milliseconds the fade transition takes (null means no transition)
  fadeDelay: 1.0          // Point during the overlay's fade-in that the modal begins to fade in (.5 = 50%, 1.5 = 150%, etc.)
};
```
So my assumption was that it was supposed to appear. But it seems not. But when I set the values manually, then it shows up
https://codepen.io/ccasalicchio/pen/wLxyNV

**Comment by kylefox** [comment]
The problem is that your code is not _updating_ the model default options, it's completely overwriting them:

```javascript
$.modal.defaults = {
    closeExisting: true,
    clickClose: false
};
```

After running this code, `$.modal.defaults.showClose` is `"undefined"`

The correct way to do this is to override the individual values you want:

```javascript
$.modal.defaults.clickClose = false;
$.modal.defaults.closeExisting = true;
```

Or by using [`jQuery.extend()`](https://api.jquery.com/jQuery.extend/) to _merge_ your settings with `$.modal.default`,  rather than overwriting it.

Example: https://codepen.io/anon/pen/mZGOZQ

**Comment by ccasalicchio** [comment]
Thank you @kylefox for the clarification!
