### ISSUE TITLE
Fetching partial HTML in AJAX?

### ISSUE THREAD

**Issue by trst** [kylefox/jquery-modal#25]
I was hoping you could lend me some insight about using .load() in place of .get() to fetch a partial from another page? Or is there perhaps a better way to implement this type of request?

To be clear, I have an external page but I only want the content of, say, div#content rather than the entire page. Any insight you could offer would be truly appreciated.

**Comment by Nuruddinjr** [comment]
This chunk of code doesn't work in my case, when clicked, debugger doesn't catch any breakpoint within this code, what can be the problem?

**Comment by kylefox** [comment]
@Nuruddinjr It's impossible to know what the problem could be without more information. Please provide more details and a publicly-accessible page that demonstrates the problem. thanks!
