### ISSUE TITLE
Compatibility with bootstrap

### ISSUE THREAD

**Issue by sekra24** [kylefox/jquery-modal#270]
Hi @kylefox I know the compatibility with bootstrap is not given because of the same namespace. Is there anything that holds you back from changing your jquery plugins namespace for bootstrap compatibility? We like your plugin but we are using yarn and gulp for packaging. So manually change the namespace would be pain in the ass if you update something.

Thank you. Best, Sebastian

**Comment by SeanDevoy** [comment]
Bump.  We love this plugin, but incompatibility with bootstrap is killing us.  Just change the name to GreatModal()??

**Comment by walialu** [comment]
KylesModal!

**Comment by SeanDevoy** [comment]
I did just edit it and change it to jqmodal.
It’s great.
Thanks.

**Comment by kylefox** [comment]
This library is no longer maintained. I'd suggest you fork and rename if the current implementation doesn't work for you.
