### ISSUE TITLE
Is there something like 'CATCH-ALL' for the events?

### ISSUE THREAD

**Issue by VARGA-Peter** [kylefox/jquery-modal#282]
Currently I am catching the events with this:

```
            $(<selector>).on(
                $.modal.BEFORE_OPEN + ' ' +
                $.modal.OPEN + ' ' +
                $.modal.AFTER_CLOSE,
                function (e) {
                        window[functionName](e);
                    }
                );

```

This means, it's very general as I differ in the callback function when it was called. This helps me to re-use the code and follow the DRY approach. 

Is there a way I can catch all of the existing events without calling them uniquely? Something like wildchars expression?

```javascript
$.modal.BEFORE_BLOCK = 'modal:before-block';    // Fires just before the overlay (blocker) appears.
$.modal.BLOCK = 'modal:block';                  // Fires after the overlay (block) is visible.
$.modal.BEFORE_OPEN = 'modal:before-open';      // Fires just before the modal opens.
$.modal.OPEN = 'modal:open';                    // Fires after the modal has finished opening.
$.modal.BEFORE_CLOSE = 'modal:before-close';    // Fires when the modal has been requested to close.
$.modal.CLOSE = 'modal:close';                  // Fires when the modal begins closing (including animations).
$.modal.AFTER_CLOSE = 'modal:after-close';      // Fires after the modal has fully closed (including animations).
```

**Comment by Zenoo** [comment]
#292 Should fix this

**Comment by kylefox** [comment]
Genuinely curious — what's the use case for this? I think before adding a feature it should be something that's widely useful, and I'm not sure I understand the reason to have wildcard event support. (I'm not aware of any other modal libraries that do this — links welcome).

**Comment by VARGA-Peter** [comment]
> Genuinely curious — what's the use case for this? I think before adding a feature it should be something that's widely useful, and I'm not sure I understand the reason to have wildcard event support. (I'm not aware of any other modal libraries that do this — links welcome).

I have for each modal window one function which handles all callbacks. So instead I write 5 functions for each callback I have in one function a switch. Therefore I have to provide all of the possible callbacks instead of one and in the function I do what I got to do.

**Comment by kylefox** [comment]
@VARGA-Peter I understand that part, but what kind of functionality do you need to run every time a modal event fires?

**Comment by kylefox** [comment]
I'm going to close this. I don't see the use-case for having a single event handler run any time the modal fire an event of any kind.
