### ISSUE TITLE
Background Page Scrolling

### ISSUE THREAD

**Issue by 4michaelcoleman** [kylefox/jquery-modal#43]
What's the best way to stop the page from scrolling when the modal dialog box is open? I want content within the box to be able to scroll but not the background (i.e. page).

**Comment by leonardoauer** [comment]
Hello Kylefox, I don't understand this. 
How am I going to attach the event $.modal.BEFORE_OPEN, when the modal does not exist yet ?
My code (it doesn't work):

	$('#delete-all-users-btn').click(function(e) {
		
		e.preventDefault();
		
		$('#del-user-confirm-modal').on($.modal.BEFORE_OPEN, function(event, modal) {
		  $('body').css('overflow', 'hidden');
		});
			
		$('#del-user-confirm-modal').on($.modal.CLOSE, function(event, modal) {
		  $('body').css('overflow', 'auto');
		});
		
		$('#del-user-confirm-modal').modal();
	});

The code above works only after $('#del-user-confirm-modal').modal(); was fired.
