### ISSUE TITLE
A problem opening a new Modal from a link within AJAX loaded content

### ISSUE THREAD

**Issue by agentfooey** [kylefox/jquery-modal#50]
Hi Kyle,

Great work on the Modal.

I am just having one problem opening a new Modal from a link inside AJAX content.

The content loaded from AJAX is contained between &lt;div class="modal"&gt;&lt;/div&gt; and nothing else above or below and doesn't include any META tags only DIVS.

Here is the link inside the Modal

&lt;a href="#open" id="open"&gt;Open&lt;/a&gt;

and the Jscript in the main document

  $('#open').click(function(event) {
        event.preventDefault();
        thisURL = "modal/content.asp";
        $.get(thisURL, function(html) {
            $(html).appendTo('body').modal();
        });
    });

Thanks for your help in advance.

Matt

**Comment by dionmes** [comment]
Hi. 
First, thx for you great work. I also can't give you an example :( (dev. environment behind fw) , but I can see also see this happening in other browsers (chrome/safari). And I see the behaviour in ajax and direct modal calls. To me it looks like the content of the modal is rendered before the contend is contained in the 'modal current' div, so the content gets actually displayed before it is hidden (which I expect is one of the attributes of the modal class before it gets faded in?). So for a brief moment you can see the content before the fading in starts.
