### ISSUE TITLE
Modal content must always be (invisible) display:none. Would be great if this was an option.

### ISSUE THREAD

**Issue by briggsm** [kylefox/jquery-modal#53]
For example:  A site may have references (anchors) to footnotes. The footnotes should always be visible.  When user clicks on the link (anchor) for a footnote, the modal should appear, and close when requested (like it does now), **but the original footnote should NOT disappear during this process**.

I think it would be ideal to have another *option* that would allow the user to control this behavior.

**Comment by kylefox** [comment]
Outside the scope of this modal — it would be easy to manually clone nodes (such as footnotes) and inject them into a modal via normal click-handlers. This is not documented in the [README](https://github.com/kylefox/jquery-modal#method-2-manually) but it should be relatively straightforward for the user to implement.
