### ISSUE TITLE
Modal exceeds browsers viewable area

### ISSUE THREAD

**Issue by jameslaws** [kylefox/jquery-modal#57]
Is there a way to make the modal only fill the viewable height of the browser if content exceeds the viewable area. Then I could implement a scroll for the content as needed. I looked around but I didn't see anything right off.

**Comment by rifer** [comment]
I'm overrriding it with this style:

```
.modal.current {
  width: 500px;
  max-height: 500px;
  overflow-y: scroll;
}

Hope it helps
```
