### ISSUE TITLE
Naming conflict with bootstrap

### ISSUE THREAD

**Issue by a1ee9b** [kylefox/jquery-modal#62]
I ran into the same issue #33 was having.  I was getting a grey, unclickable background but the modal wouldn't show.

The problem seems to be the name of the plugin because it runs into a naming conflict with Bootstrap! So I replaced every occurrence of the word "modal" with "jmodal" in the plugin and now it works as expected.

I suggest using another variable for the global namespace, since bootstrap is widely used.

P.S.: I opened a new issue so people using bootstrap will find the solution faster.

**Comment by Luc45** [comment]
I didn't understand the bootstrap solution, what do you mean by renaming the plugin?
