### ISSUE TITLE
Open modal with <button>

### ISSUE THREAD

**Issue by hmaesta** [kylefox/jquery-modal#74]
Hello.

How can I open a modal with a `<button>` instead of an `<a>`?

Thank you.

**Comment by wzup** [comment]
@hmaesta How about React?

**Comment by kylefox** [comment]
@wzup That error looks like either jQuery or (more likely) jQuery Modal isn't loaded. Please double check that you've included the necessary `<script>` tags and that your call to `$.modal()` is executing within a context where the libraries are loaded, i.e. inside a `$(function() { ... });`
