### ISSUE TITLE
Reuse HTML?

### ISSUE THREAD

**Issue by amcsi** [kylefox/jquery-modal#88]
How can I open a modal, but reusing the same HTML each time I open it?

I currently have click events registered to some elements in the modal template that always work when the modal is first open, but for successive opens they don't work anymore. I even confirmed in Google Chrome that the elements from the first open and the second open are different.

**Comment by mtkennedy** [comment]
Same issue.  Using the Ajax method to open the modal, once you close it and re-open the same one  Fadein doesn't work, showclose, etc... also any js/jquery in the modal itself works the first time, but not after you close and reopen the modal.

**Comment by mtkennedy** [comment]
I fixed this on mine.  I made links with the class destroymodal to close the modal and added this bit of jquery.  Without this, the modal was left in the DOM after closing, and the next time it was opened it just made another with the class "modal current" while the previous "modal" was left behind interferring with the new one.   

$('.destroymodal').click(function(){
	$('.modal').remove();
});
