### ISSUE TITLE
Flash of v-scrollbar shortly

### ISSUE THREAD

**Issue by ohmish** [kylefox/jquery-modal#95]
First:
Great work Sir. So compact and effective :)

When I use jquery-modal on a page that does not exceed browser/window height (has no vertical scrollbar), the overlay flashes a scrollbar just before opening the modal
I guess it adds the modal to the body, then adjusts it afterwards
This makes the whole page shake back and forth, shortly but very noticeable
When the root page exceeds browser height, then the problem is not there

**Comment by kylefox** [comment]
As described in the README, please provide a link to a publicly-accessibly page which demonstrates the bug. Thank you!

**Comment by ohmish** [comment]
Hi. After a lot of investigation, I found it
My overlay page was including <div class="modal"> etc. from an other file (php. dynamic pages)
Now I moved the <div class="modal"> to the very first page launched by modal, and the problem is gone
I guess jquery-modal does not wait for the full content (including external pages) to be loaded before launching the overlay
Oh well, I can live with this ;)

**Comment by kylefox** [comment]
Thanks for the update, glad you got it working!
