### ISSUE TITLE
Ability to add an additional(temporary) class to modal on close 

### ISSUE THREAD

**Issue by BenComicGraphics** [kylefox/jquery-modal#96]
Basically, I want to add a custom css transistion/fadeout/slide on the modal on close, and the ability to temporarily add a class to a closing modal(as long as the transition), then have it revert to display: none would be great.

**Comment by kylefox** [comment]
You should be able to accomplish this using the [built-in Events](https://github.com/kylefox/jquery-modal#events) and customizing the CSS file.

**Comment by BenComicGraphics** [comment]
I attempted this; the clsoe event clears out all other classes immediately.

**Comment by kylefox** [comment]
Doing something like this will apply the class to the modal when the close operation is about to begin. The class will remain on the modal even after the modal is closed, until you remove it:

```javascript
$('#my-modal').on($.modal.BEFORE_CLOSE, function(event, modal) {
    modal.elm.addClass("modal-closing");
});
```

(I just verified this behaviour on the [demo](http://kylefox.ca/jquery-modal/examples/index.html).)

Unfortunately, if the events don't suit your needs you'll need to fork this project or use a more sophisticated modal library like [colorbox](http://www.jacklmoore.com/colorbox/).

**Comment by BenComicGraphics** [comment]
That works!

[image: photo]
*Ben Carver*
Front-End Developer | *Steadfast Creative *
p: 817.962.2236 ext 7 | e: ben@steadfastcreative.com
a: 201 town center lane | suite 1107 | keller, texas 76248
[image: Facebook] <http://www.facebook.com/steadfastcreative> [image:
Twitter] <http://www.twitter.com/steadfastc> [image: Instagram]
<http://www.instagram.com/steadfastc>
