### ISSUE TITLE
Possible to open specific modal via hash?

### ISSUE THREAD

**Issue by BenComicGraphics** [kylefox/jquery-modal#97]
Let's say I have 10 modals on a page, each being opened normally via the rel="modal:open" method.  But I want to have a link to this page, like:
website.com/page#modal-1 and have the modal with the id "modal-1" automatically open. How can I go about doing this? 

Same with modals 2-10 as well.

**Comment by BenComicGraphics** [comment]
I got it working.  

if(window.location.hash) { 
  var hash = window.location.hash;
  $(hash).modal();
}

**Comment by kylefox** [comment]
Cool idea!
