### ISSUE TITLE
Closing ajax-loaded modal on event 

### ISSUE THREAD

**Issue by pavelplzak** [kylefox/jquery-modal#99]
Hello, I'm having problem with closing modal which has been loaded by ajax. I'm doing so inside an event OPEN:

$(document).on($.modal.OPEN, function (event, modal) {
	$.modal.close();
});

It's just example, I actually want to setup handler which will close modal after ajax-submitted form inside that modal, but it's not important for the demonstration, this simple example doesn't work either. When I don't use ajax for opening modal, it works. 

Any ideas? Thanks a lot.

**Comment by kylefox** [comment]
Please link to a publicly-accessible page demonstrating the bug. From the [README](https://github.com/kylefox/jquery-modal#found-a-bug-meh):

> [Dropbox](https://www.dropbox.com) or [JSFiddle](http://jsfiddle.net/) work well for demonstrating reproducable bugs, but you can use anything as long as it's public.

Thanks!
